# Generated by Django 3.0.8 on 2020-07-03 14:58

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True, verbose_name='Data di creazione')),
                ('title', models.CharField(max_length=150, unique=True, verbose_name="Titolo dell'articolo")),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('content', ckeditor.fields.RichTextField()),
            ],
        ),
    ]
