# Generated by Django 3.0.8 on 2020-07-03 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='slug',
            field=models.CharField(default='default', max_length=150, unique=True, verbose_name='URL'),
            preserve_default=False,
        ),
    ]
